### ISSUE TITLE
Implement Day Parser

### ISSUE THREAD

**Issue by eliteGoblin** [eliteGoblin/lyubishchev#6]
# Background

Low level的Fetcher完成，Data Reader作为上一层， 调用其取得time series, 并将其转化成为Day Records

# Idea && Solution

*  Generate Day Records
*  Search, filter function
*  Write unit test

# TODO

- [x] Run CI by commenting out testing functions  parse_and_generate_day_records
- [x] Add unit test for util functions if needed
*  add test test_find_first_match_event
*  add test test_find_first_match_time_intervals
- [x] put single day parsing logic into parse_and_generate_day_record
- [ ] unit test: `parse_and_generate_day_record`
- [ ] unit test: `parse_and_generate_day_records`
- [ ] Add e2e logic to get Day Records out of Clockify
