### ISSUE TITLE
Visualize time_intervals summary and filter results using Jupyter

### ISSUE THREAD

**Issue by eliteGoblin** [eliteGoblin/lyubishchev#8]
Aim to create a place I can playwith my data

# TODO

- [x] Piechart for time stat, add total hours data aside. 
Time span XY plot

Implement following in separate groups: 

- [x] Effective Output
- [x] Calm:  walk, meditation, exercise
- [x] sex,  connection
- [x]  sleep: night, nap
- [x] numb, dispute, distracted

# Solution

*  Think, consolidate requirement first

# Time stat pie chart

As a user, I want to show a piechart of time breakup: 

![image.png](https://images.zenhubusercontent.com/5ea828a0f739259b2b0f4f24/e5788a77-5d31-4bf4-861c-eb26991ff457)

# Time plot

## Effective output

In same plot, shows: 
*  X: day 
*  Y: spans of work, SE, work+SE

## Supporting

*  Walk 
*  Meditation
*  nap, sleep
*  Sex
*  Exercise

## Metric

*  Wakeup, bed timestamp
